on:
  workflow_dispatch:
jobs:
  scan_with_qscanner:
    name: Scan with QScanner
    runs-on: ubuntu-22.04  
    steps:
      - name: Download QScanner
        run: |
          curl -Lk https://www.qualys.com/qscanner/download/${{ vars.QSCANNER_VERSION }}/download_qscanner.sh -O ${{ github.workspace }}/QScannerBinary/download_qscanner.sh
          chmod +x ${{ github.workspace }}/QScannerBinary/download_qscanner.sh
          ./${{ github.workspace }}/QScannerBinary/download_qscanner.sh
      - name: Launch Scan
        run: |
          ./${{ github.workspace }}/QScannerBinary/linux-amd64/qscanner image ${{ vars.IMAGE_TO_SCAN }} \
            --mode get-report \
            --pod ${{ vars.POD }} \
            --access-token ${{ secrets.QUALYS_ACCESS_TOKEN }} \
            --log-level debug \
            --poll-wait-interval 30s     
      - name: Save cache
        id: qscanner-cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/qualys/qscanner
          key: qscanner-cache
