on:
  push:
  workflow_dispatch:
jobs:
  scan_with_qscanner:
    name: Scan with QScanner
    runs-on: ubuntu-22.04  
    steps:
      - uses: actions/cache/restore@v4
        id: qscanner-cache-id
        with:
          path: ~/.cache/qualys/qscanner
          key: qscanner-cache   
      - uses: actions/cache/restore@v4
        id: binary-cache-id
        with:
          path: linux-amd64
          key: binary-${{ vars.QSCANNER_VERSION }}-cache             
      - name: Download QScanner
        if: steps.binary-cache.outputs.cache-hit != 'true'
        run: |
          curl -LOk https://www.qualys.com/qscanner/download/${{ vars.QSCANNER_VERSION }}/download_qscanner.sh 
          chmod +x download_qscanner.sh
          ./download_qscanner.sh           
      - name: Launch Scan
        run: |
          ./linux-amd64/qscanner image ${{ vars.IMAGE_TO_SCAN }} \
            --mode get-report \
            --pod ${{ vars.POD }} \
            --access-token ${{ secrets.QUALYS_ACCESS_TOKEN }} \
            --cache local \
            --log-level ${{ vars.LOG_LEVEL }} \
            --poll-wait-interval 30s   
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: qualys/qscanner/data/*-Report.sarif.json            
      - name: Save QScanner cache
        id: qscanner-cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/qualys/qscanner
          key: qscanner-cache
      - name: Save Binary cache
        id: binary-cache
        uses: actions/cache@v4
        with:
          path: linux-amd64
          key: binary-${{ vars.QSCANNER_VERSION }}-cache
