on:
  workflow_dispatch:
jobs:
  scan_with_qscanner:
    name: Scan with QScanner
    runs-on: ubuntu-22.04  
    steps:
      - name: Download QScanner
        run: |
          curl -LOk https://www.qualys.com/qscanner/download/${{ vars.QSCANNER_VERSION }}/download_qscanner.sh
          chmod +x download_qscanner.sh
          ./download_qscanner.sh
